import Link from "next/link";
import DataStore from "./context";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head><link href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css" rel="stylesheet"></link></head>
            <body suppressHydrationWarning>
                <DataStore>{children}</DataStore>
            </body>
        </html>
    );
}